### PR TITLE
Update testdata to work with latest keycloak image

### PR DESCRIPTION
**Pull request by dj5k**
Not sure when it last worked but when I tried running tests today I ran into several issues.

This is the minimal set of changes I needed to make to get tests up and running (and passing) again on my machine.

### CODE REVIEW

**Comment by Nerzal** [comment]
What happens, when you run the tests using the docker-compose file?
There also is a Makefile for that

**Comment by dj5k** [comment]
I can sure try!

Where can I find that stuff? :)

**Comment by Nerzal** [comment]
The Makefile and the docker-compose.yml both reside in the root of the project. 

You could just try to run

> make start-keycloak

(after some seconds wait for startup)

> make test

**Comment by dj5k** [comment]
It feels like I am missing something or am misunderstanding you.
This is what the tree of this project looks like for me:
```
❯ tree .
.
├── gocloaksession.go
├── go.mod
├── go.sum
├── LICENSE
├── README.md
├── session.go
├── session_test.go
└── testdata
    └── gocloak-realm.json

1 directory, 9 files

```

Are you referring to the files over in the gocloak project?

**Comment by Nerzal** [comment]
Oh i'm sorry, i thought this is the gocloak repository itself. 
But this is a good reminder, that we should also add such a makefile here.

**Comment by Nerzal** [comment]
Merged the change, thank you!

**Comment by dj5k** [comment]
thanks for clarification :) happy to help!

P.S.: I am building an additional `NewAdminSession` function for internal needs (see also my comment [here](https://github.com/Nerzal/gocloak/issues/276#issuecomment-1505060984) ). Would you be interested in that as a contribution?

**Pull request merged**
